//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GospWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    using System.Threading.Tasks;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kiosk", Namespace="http://schemas.datacontract.org/2004/07/GospService")]
    [System.SerializableAttribute()]
    public partial class Kiosk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdKioskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdosnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdtexeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GospWebApp.ServiceReference1.Schetchik SchetchikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GospWebApp.ServiceReference1.Schetchik Schetchik1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GospWebApp.ServiceReference1.Schetchik[] Schetchik2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> arendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nomerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKiosk {
            get {
                return this.IdKioskField;
            }
            set {
                if ((this.IdKioskField.Equals(value) != true)) {
                    this.IdKioskField = value;
                    this.RaisePropertyChanged("IdKiosk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ide {
            get {
                return this.IdeField;
            }
            set {
                if ((this.IdeField.Equals(value) != true)) {
                    this.IdeField = value;
                    this.RaisePropertyChanged("Ide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Idosn {
            get {
                return this.IdosnField;
            }
            set {
                if ((this.IdosnField.Equals(value) != true)) {
                    this.IdosnField = value;
                    this.RaisePropertyChanged("Idosn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Idtexe {
            get {
                return this.IdtexeField;
            }
            set {
                if ((this.IdtexeField.Equals(value) != true)) {
                    this.IdtexeField = value;
                    this.RaisePropertyChanged("Idtexe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GospWebApp.ServiceReference1.Schetchik Schetchik {
            get {
                return this.SchetchikField;
            }
            set {
                if ((object.ReferenceEquals(this.SchetchikField, value) != true)) {
                    this.SchetchikField = value;
                    this.RaisePropertyChanged("Schetchik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GospWebApp.ServiceReference1.Schetchik Schetchik1 {
            get {
                return this.Schetchik1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Schetchik1Field, value) != true)) {
                    this.Schetchik1Field = value;
                    this.RaisePropertyChanged("Schetchik1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GospWebApp.ServiceReference1.Schetchik[] Schetchik2 {
            get {
                return this.Schetchik2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Schetchik2Field, value) != true)) {
                    this.Schetchik2Field = value;
                    this.RaisePropertyChanged("Schetchik2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> arenda {
            get {
                return this.arendaField;
            }
            set {
                if ((this.arendaField.Equals(value) != true)) {
                    this.arendaField = value;
                    this.RaisePropertyChanged("arenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nomer {
            get {
                return this.nomerField;
            }
            set {
                if ((this.nomerField.Equals(value) != true)) {
                    this.nomerField = value;
                    this.RaisePropertyChanged("nomer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schetchik", Namespace="http://schemas.datacontract.org/2004/07/GospService")]
    [System.SerializableAttribute()]
    public partial class Schetchik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSchetchikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GospWebApp.ServiceReference1.Kiosk[] KioskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GospWebApp.ServiceReference1.Kiosk[] Kiosk1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GospWebApp.ServiceReference1.Kiosk Kiosk2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> T1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> T2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] texuchetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdK {
            get {
                return this.IdKField;
            }
            set {
                if ((this.IdKField.Equals(value) != true)) {
                    this.IdKField = value;
                    this.RaisePropertyChanged("IdK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSchetchik {
            get {
                return this.IdSchetchikField;
            }
            set {
                if ((this.IdSchetchikField.Equals(value) != true)) {
                    this.IdSchetchikField = value;
                    this.RaisePropertyChanged("IdSchetchik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GospWebApp.ServiceReference1.Kiosk[] Kiosk {
            get {
                return this.KioskField;
            }
            set {
                if ((object.ReferenceEquals(this.KioskField, value) != true)) {
                    this.KioskField = value;
                    this.RaisePropertyChanged("Kiosk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GospWebApp.ServiceReference1.Kiosk[] Kiosk1 {
            get {
                return this.Kiosk1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Kiosk1Field, value) != true)) {
                    this.Kiosk1Field = value;
                    this.RaisePropertyChanged("Kiosk1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GospWebApp.ServiceReference1.Kiosk Kiosk2 {
            get {
                return this.Kiosk2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Kiosk2Field, value) != true)) {
                    this.Kiosk2Field = value;
                    this.RaisePropertyChanged("Kiosk2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> T1 {
            get {
                return this.T1Field;
            }
            set {
                if ((this.T1Field.Equals(value) != true)) {
                    this.T1Field = value;
                    this.RaisePropertyChanged("T1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> T2 {
            get {
                return this.T2Field;
            }
            set {
                if ((this.T2Field.Equals(value) != true)) {
                    this.T2Field = value;
                    this.RaisePropertyChanged("T2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ts {
            get {
                return this.TsField;
            }
            set {
                if ((this.TsField.Equals(value) != true)) {
                    this.TsField = value;
                    this.RaisePropertyChanged("Ts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nomer {
            get {
                return this.nomerField;
            }
            set {
                if ((this.nomerField.Equals(value) != true)) {
                    this.nomerField = value;
                    this.RaisePropertyChanged("nomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] texuchet {
            get {
                return this.texuchetField;
            }
            set {
                if ((object.ReferenceEquals(this.texuchetField, value) != true)) {
                    this.texuchetField = value;
                    this.RaisePropertyChanged("texuchet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGospService")]
    public interface IGospService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/GetAllUser", ReplyAction="http://tempuri.org/IGospService/GetAllUserResponse")]
        GospWebApp.ServiceReference1.Kiosk[] GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/GetAllUser", ReplyAction="http://tempuri.org/IGospService/GetAllUserResponse")]
        System.Threading.Tasks.Task<GospWebApp.ServiceReference1.Kiosk[]> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/AddUser", ReplyAction="http://tempuri.org/IGospService/AddUserResponse")]
        int AddUser(int? Nomer, string Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/AddUser", ReplyAction="http://tempuri.org/IGospService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(int? Nomer, string Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/GetAllUserById", ReplyAction="http://tempuri.org/IGospService/GetAllUserByIdResponse")]
        GospWebApp.ServiceReference1.Kiosk GetAllUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/GetAllUserById", ReplyAction="http://tempuri.org/IGospService/GetAllUserByIdResponse")]
        System.Threading.Tasks.Task<GospWebApp.ServiceReference1.Kiosk> GetAllUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/UpdateUser", ReplyAction="http://tempuri.org/IGospService/UpdateUserResponse")]
        int UpdateUser(int Id, int? Nomer, string Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/UpdateUser", ReplyAction="http://tempuri.org/IGospService/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(int Id, int? Nomer, string Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/DeleteUserById", ReplyAction="http://tempuri.org/IGospService/DeleteUserByIdResponse")]
        int DeleteUserById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGospService/DeleteUserById", ReplyAction="http://tempuri.org/IGospService/DeleteUserByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteUserByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGospServiceChannel : GospWebApp.ServiceReference1.IGospService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GospServiceClient : System.ServiceModel.ClientBase<GospWebApp.ServiceReference1.IGospService>, GospWebApp.ServiceReference1.IGospService {
        
        public GospServiceClient() {
        }
        
        public GospServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GospServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GospServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GospServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GospWebApp.ServiceReference1.Kiosk[] GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<GospWebApp.ServiceReference1.Kiosk[]> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public int AddUser(int? Nomer, string Model) {
            return base.Channel.AddUser(Nomer, Model);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(int? Nomer, string Model) {
            return base.Channel.AddUserAsync(Nomer, Model);
        }
        
        public GospWebApp.ServiceReference1.Kiosk GetAllUserById(int id) {
            return base.Channel.GetAllUserById(id);
        }
        
        public System.Threading.Tasks.Task<GospWebApp.ServiceReference1.Kiosk> GetAllUserByIdAsync(int id) {
            return base.Channel.GetAllUserByIdAsync(id);
        }
        
        public int UpdateUser(int Id, int? Nomer, string Model) {
            return base.Channel.UpdateUser(Id, Nomer, Model);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(int Id, int? Nomer, string Model) {
            return base.Channel.UpdateUserAsync(Id, Nomer, Model);
        }
        
        public int DeleteUserById(int Id) {
            return base.Channel.DeleteUserById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserByIdAsync(int Id) {
            return base.Channel.DeleteUserByIdAsync(Id);
        }

    }
}
