//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GospService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk
    {
        public Kiosk()
        {
            this.Schetchik2 = new HashSet<Schetchik>();
        }
    
        public int IdKiosk { get; set; }
        public Nullable<int> nomer { get; set; }
        public Nullable<int> Ide { get; set; }
        public Nullable<int> Idosn { get; set; }
        public Nullable<int> Idtexe { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> arenda { get; set; }
    
        public virtual Schetchik Schetchik { get; set; }
        public virtual Schetchik Schetchik1 { get; set; }
        public virtual ICollection<Schetchik> Schetchik2 { get; set; }
    }
}
