//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GospService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schetchik
    {
        public Schetchik()
        {
            this.Kiosk = new HashSet<Kiosk>();
            this.Kiosk1 = new HashSet<Kiosk>();
        }
    
        public int IdSchetchik { get; set; }
        public Nullable<int> nomer { get; set; }
        public string model { get; set; }
        public Nullable<decimal> T1 { get; set; }
        public Nullable<decimal> T2 { get; set; }
        public Nullable<decimal> Ts { get; set; }
        public Nullable<int> IdK { get; set; }
        public byte[] texuchet { get; set; }
    
        public virtual ICollection<Kiosk> Kiosk { get; set; }
        public virtual ICollection<Kiosk> Kiosk1 { get; set; }
        public virtual Kiosk Kiosk2 { get; set; }
    }
}
